language:  python
python:
  - "3.3"
virtualenf:
  system_site_packages: true
before_install:  
  - "sudo apt-get update"
install:  
  - "pip install -r requirements.txt"
script:
  - "./testTravis.py"
notifications:
  email: 
    - livysdad27@gmail.com
