language:  python
python:
  - "2.7"
virtualenf:
  system_site_packages: true
before_install:  
  - "sudo apt-get update"
install:  
  - "pip install -r requirements.txt"
script:
  - "nose2 -v"
notifications:
  email: 
    - livysdad27@gmail.com
